# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 893)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 20, 1021, 791))
        self.stackedWidget.setObjectName("stackedWidget")
        self.data_page = QtWidgets.QWidget()
        self.data_page.setStyleSheet("")
        self.data_page.setObjectName("data_page")
        self.data_set_label = QtWidgets.QLabel(self.data_page)
        self.data_set_label.setGeometry(QtCore.QRect(310, 0, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.data_set_label.setFont(font)
        self.data_set_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_set_label.setObjectName("data_set_label")
        self.stackedWidget.addWidget(self.data_page)
        self.hist_page = QtWidgets.QWidget()
        self.hist_page.setStyleSheet("")
        self.hist_page.setObjectName("hist_page")
        self.histogram_label = QtWidgets.QLabel(self.hist_page)
        self.histogram_label.setGeometry(QtCore.QRect(220, 20, 571, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.histogram_label.setFont(font)
        self.histogram_label.setAlignment(QtCore.Qt.AlignCenter)
        self.histogram_label.setObjectName("histogram_label")
        self.stackedWidget.addWidget(self.hist_page)
        self.heat_page = QtWidgets.QWidget()
        self.heat_page.setObjectName("heat_page")
        self.heat_map_label = QtWidgets.QLabel(self.heat_page)
        self.heat_map_label.setGeometry(QtCore.QRect(330, 20, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.heat_map_label.setFont(font)
        self.heat_map_label.setAlignment(QtCore.Qt.AlignCenter)
        self.heat_map_label.setObjectName("heat_map_label")
        self.stackedWidget.addWidget(self.heat_page)
        self.train_cloud_page = QtWidgets.QWidget()
        self.train_cloud_page.setObjectName("train_cloud_page")
        self.train_cloud_label = QtWidgets.QLabel(self.train_cloud_page)
        self.train_cloud_label.setGeometry(QtCore.QRect(250, 10, 491, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.train_cloud_label.setFont(font)
        self.train_cloud_label.setAlignment(QtCore.Qt.AlignCenter)
        self.train_cloud_label.setObjectName("train_cloud_label")
        self.stackedWidget.addWidget(self.train_cloud_page)
        self.test_cloud_page = QtWidgets.QWidget()
        self.test_cloud_page.setObjectName("test_cloud_page")
        self.test_cloud_label = QtWidgets.QLabel(self.test_cloud_page)
        self.test_cloud_label.setGeometry(QtCore.QRect(320, 10, 381, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.test_cloud_label.setFont(font)
        self.test_cloud_label.setAlignment(QtCore.Qt.AlignCenter)
        self.test_cloud_label.setObjectName("test_cloud_label")
        self.stackedWidget.addWidget(self.test_cloud_page)
        self.check_page = QtWidgets.QWidget()
        self.check_page.setObjectName("check_page")
        self.check_message_label = QtWidgets.QLabel(self.check_page)
        self.check_message_label.setGeometry(QtCore.QRect(300, 10, 411, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.check_message_label.setFont(font)
        self.check_message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.check_message_label.setObjectName("check_message_label")
        self.message_text_field = QtWidgets.QLineEdit(self.check_page)
        self.message_text_field.setGeometry(QtCore.QRect(80, 260, 851, 81))
        self.message_text_field.setStyleSheet("background-color: rgb(211, 215, 207)")
        self.message_text_field.setObjectName("message_text_field")
        self.label = QtWidgets.QLabel(self.check_page)
        self.label.setGeometry(QtCore.QRect(410, 180, 191, 51))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.check_message_button = QtWidgets.QPushButton(self.check_page)
        self.check_message_button.setGeometry(QtCore.QRect(420, 380, 171, 81))
        self.check_message_button.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.check_message_button.setObjectName("check_message_button")
        self.result_label = QtWidgets.QLabel(self.check_page)
        self.result_label.setGeometry(QtCore.QRect(360, 560, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.result_label.setFont(font)
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.stackedWidget.addWidget(self.check_page)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 830, 991, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.data_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.data_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.data_button.setObjectName("data_button")
        self.horizontalLayout.addWidget(self.data_button)
        self.hist_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.hist_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.hist_button.setObjectName("hist_button")
        self.horizontalLayout.addWidget(self.hist_button)
        self.heat_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.heat_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.heat_button.setObjectName("heat_button")
        self.horizontalLayout.addWidget(self.heat_button)
        self.train_cloud_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.train_cloud_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.train_cloud_button.setObjectName("train_cloud_button")
        self.horizontalLayout.addWidget(self.train_cloud_button)
        self.test_cloud_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.test_cloud_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.test_cloud_button.setObjectName("test_cloud_button")
        self.horizontalLayout.addWidget(self.test_cloud_button)
        self.check_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.check_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.check_button.setObjectName("check_button")
        self.horizontalLayout.addWidget(self.check_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.data_set_label.setText(_translate("MainWindow", "Data Set of Spam SMS Messages"))
        self.histogram_label.setText(_translate("MainWindow", "Histogram Data"))
        self.heat_map_label.setText(_translate("MainWindow", "Heat Map of Test Data"))
        self.train_cloud_label.setText(_translate("MainWindow", "Training Data Set Word Cloud"))
        self.test_cloud_label.setText(_translate("MainWindow", "Test Data Set Word Cloud"))
        self.check_message_label.setText(_translate("MainWindow", "Check Message Below"))
        self.label.setText(_translate("MainWindow", "Enter You message below:"))
        self.check_message_button.setText(_translate("MainWindow", "Spam check!"))
        self.result_label.setText(_translate("MainWindow", "RESULT"))
        self.data_button.setText(_translate("MainWindow", "Test Data"))
        self.hist_button.setText(_translate("MainWindow", "Histogram"))
        self.heat_button.setText(_translate("MainWindow", "Heat Map"))
        self.train_cloud_button.setText(_translate("MainWindow", "Training Word Cloud"))
        self.test_cloud_button.setText(_translate("MainWindow", "Test Set Word Cloud"))
        self.check_button.setText(_translate("MainWindow", "Check Message"))

