# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 893)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 20, 1021, 791))
        self.stackedWidget.setObjectName("stackedWidget")
        self.data_page = QtWidgets.QWidget()
        self.data_page.setStyleSheet("")
        self.data_page.setObjectName("data_page")
        self.data_set_label = QtWidgets.QLabel(self.data_page)
        self.data_set_label.setGeometry(QtCore.QRect(310, 0, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.data_set_label.setFont(font)
        self.data_set_label.setStyleSheet("color: #ff007f;")
        self.data_set_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_set_label.setObjectName("data_set_label")
        self.frame = QtWidgets.QFrame(self.data_page)
        self.frame.setGeometry(QtCore.QRect(720, 100, 241, 671))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 29, 201, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.accuracy_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.accuracy_label.setStyleSheet("color: #ff007f;")
        self.accuracy_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.accuracy_label.setObjectName("accuracy_label")
        self.verticalLayout.addWidget(self.accuracy_label)
        self.precision_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.precision_label.setStyleSheet("color: #ff007f;")
        self.precision_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.precision_label.setObjectName("precision_label")
        self.verticalLayout.addWidget(self.precision_label)
        self.recall_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.recall_label.setStyleSheet("color: #ff007f;")
        self.recall_label.setObjectName("recall_label")
        self.verticalLayout.addWidget(self.recall_label)
        self.f1_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.f1_label.setStyleSheet("color: #ff007f;")
        self.f1_label.setObjectName("f1_label")
        self.verticalLayout.addWidget(self.f1_label)
        self.data_set_table = QtWidgets.QTableView(self.data_page)
        self.data_set_table.setGeometry(QtCore.QRect(20, 100, 661, 671))
        self.data_set_table.setStyleSheet("color: #ff007f;")
        self.data_set_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.data_set_table.setObjectName("data_set_table")
        self.stackedWidget.addWidget(self.data_page)
        self.hist_page = QtWidgets.QWidget()
        self.hist_page.setStyleSheet("")
        self.hist_page.setObjectName("hist_page")
        self.histogram_label = QtWidgets.QLabel(self.hist_page)
        self.histogram_label.setGeometry(QtCore.QRect(220, 0, 571, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.histogram_label.setFont(font)
        self.histogram_label.setStyleSheet("color: #ff007f;")
        self.histogram_label.setAlignment(QtCore.Qt.AlignCenter)
        self.histogram_label.setObjectName("histogram_label")
        self.hist_widget = QtWidgets.QWidget(self.hist_page)
        self.hist_widget.setGeometry(QtCore.QRect(70, 80, 901, 701))
        self.hist_widget.setObjectName("hist_widget")
        self.stackedWidget.addWidget(self.hist_page)
        self.heat_page = QtWidgets.QWidget()
        self.heat_page.setObjectName("heat_page")
        self.heat_map_label = QtWidgets.QLabel(self.heat_page)
        self.heat_map_label.setGeometry(QtCore.QRect(340, -10, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.heat_map_label.setFont(font)
        self.heat_map_label.setStyleSheet("color: #ff007f;")
        self.heat_map_label.setAlignment(QtCore.Qt.AlignCenter)
        self.heat_map_label.setObjectName("heat_map_label")
        self.heat_widget = QtWidgets.QWidget(self.heat_page)
        self.heat_widget.setGeometry(QtCore.QRect(60, 90, 911, 691))
        self.heat_widget.setObjectName("heat_widget")
        self.stackedWidget.addWidget(self.heat_page)
        self.train_cloud_page = QtWidgets.QWidget()
        self.train_cloud_page.setObjectName("train_cloud_page")
        self.train_cloud_label = QtWidgets.QLabel(self.train_cloud_page)
        self.train_cloud_label.setGeometry(QtCore.QRect(250, -20, 491, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.train_cloud_label.setFont(font)
        self.train_cloud_label.setStyleSheet("color: #ff007f;")
        self.train_cloud_label.setAlignment(QtCore.Qt.AlignCenter)
        self.train_cloud_label.setObjectName("train_cloud_label")
        self.train_cloud_widget = QtWidgets.QWidget(self.train_cloud_page)
        self.train_cloud_widget.setGeometry(QtCore.QRect(50, 80, 911, 681))
        self.train_cloud_widget.setObjectName("train_cloud_widget")
        self.stackedWidget.addWidget(self.train_cloud_page)
        self.test_cloud_page = QtWidgets.QWidget()
        self.test_cloud_page.setObjectName("test_cloud_page")
        self.test_cloud_label = QtWidgets.QLabel(self.test_cloud_page)
        self.test_cloud_label.setGeometry(QtCore.QRect(320, -20, 381, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.test_cloud_label.setFont(font)
        self.test_cloud_label.setStyleSheet("color: #ff007f;")
        self.test_cloud_label.setAlignment(QtCore.Qt.AlignCenter)
        self.test_cloud_label.setObjectName("test_cloud_label")
        self.test_cloud_widget = QtWidgets.QWidget(self.test_cloud_page)
        self.test_cloud_widget.setGeometry(QtCore.QRect(40, 90, 931, 681))
        self.test_cloud_widget.setObjectName("test_cloud_widget")
        self.stackedWidget.addWidget(self.test_cloud_page)
        self.check_page = QtWidgets.QWidget()
        self.check_page.setObjectName("check_page")
        self.check_message_label = QtWidgets.QLabel(self.check_page)
        self.check_message_label.setGeometry(QtCore.QRect(300, 10, 411, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.check_message_label.setFont(font)
        self.check_message_label.setStyleSheet("color: #ff007f;")
        self.check_message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.check_message_label.setObjectName("check_message_label")
        self.message_text_field = QtWidgets.QLineEdit(self.check_page)
        self.message_text_field.setGeometry(QtCore.QRect(80, 260, 851, 81))
        self.message_text_field.setStyleSheet("background-color: rgb(211, 215, 207)")
        self.message_text_field.setObjectName("message_text_field")
        self.label = QtWidgets.QLabel(self.check_page)
        self.label.setGeometry(QtCore.QRect(410, 180, 191, 51))
        self.label.setStyleSheet("color: #ff007f;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.check_message_button = QtWidgets.QPushButton(self.check_page)
        self.check_message_button.setGeometry(QtCore.QRect(420, 380, 171, 81))
        self.check_message_button.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.check_message_button.setObjectName("check_message_button")
        self.result_label = QtWidgets.QLabel(self.check_page)
        self.result_label.setGeometry(QtCore.QRect(170, 560, 691, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.result_label.setFont(font)
        self.result_label.setStyleSheet("color: #ff007f;")
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.stackedWidget.addWidget(self.check_page)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 830, 991, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.data_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.data_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.data_button.setObjectName("data_button")
        self.horizontalLayout.addWidget(self.data_button)
        self.hist_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.hist_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.hist_button.setObjectName("hist_button")
        self.horizontalLayout.addWidget(self.hist_button)
        self.heat_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.heat_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.heat_button.setObjectName("heat_button")
        self.horizontalLayout.addWidget(self.heat_button)
        self.train_cloud_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.train_cloud_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.train_cloud_button.setObjectName("train_cloud_button")
        self.horizontalLayout.addWidget(self.train_cloud_button)
        self.test_cloud_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.test_cloud_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.test_cloud_button.setObjectName("test_cloud_button")
        self.horizontalLayout.addWidget(self.test_cloud_button)
        self.check_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.check_button.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.check_button.setObjectName("check_button")
        self.horizontalLayout.addWidget(self.check_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.data_set_label.setText(_translate("MainWindow", "Data Set of Spam SMS Messages"))
        self.accuracy_label.setText(_translate("MainWindow", "Accuracy Score:"))
        self.precision_label.setText(_translate("MainWindow", "Precision Score:"))
        self.recall_label.setText(_translate("MainWindow", "Recall Score:"))
        self.f1_label.setText(_translate("MainWindow", "F1 Score:"))
        self.histogram_label.setText(_translate("MainWindow", "Histogram Data"))
        self.heat_map_label.setText(_translate("MainWindow", "Heat Map of Test Data"))
        self.train_cloud_label.setText(_translate("MainWindow", "Training Data Set Word Cloud"))
        self.test_cloud_label.setText(_translate("MainWindow", "Test Data Set Word Cloud"))
        self.check_message_label.setText(_translate("MainWindow", "Message Checking Tool"))
        self.label.setText(_translate("MainWindow", "Enter You message below:"))
        self.check_message_button.setText(_translate("MainWindow", "Spam check!"))
        self.result_label.setText(_translate("MainWindow", "Your result will show up here as either \"Spam\" or \"Ham\""))
        self.data_button.setText(_translate("MainWindow", "Test Data"))
        self.hist_button.setText(_translate("MainWindow", "Histogram"))
        self.heat_button.setText(_translate("MainWindow", "Heat Map"))
        self.train_cloud_button.setText(_translate("MainWindow", "Training Word Cloud"))
        self.test_cloud_button.setText(_translate("MainWindow", "Test Set Word Cloud"))
        self.check_button.setText(_translate("MainWindow", "Check Message"))

